import type { Locale } from '../../../i18n'

/**
 * Los textos del jugador dentro de la hoja del reto y de los minijuegos que
 * llevan avisos con datos (contadores, segundos, niveles).
 *
 * Por qué un diccionario propio y no el puente de idioma
 * (`i18n/legacySpanishBridge.ts`): el puente sólo traduce un texto ya pintado si
 * es IDÉNTICO a una clave suya, y un aviso como «Nivel 3 de 5. Observa...» lleva
 * el 3 y el 5 dentro. Ahí se quedaba en castellano en una misión en gallego, y
 * los que un día se escribieron directamente en gallego (`Saíches a media
 * proba…`) salían en gallego en una misión en castellano: pantallas con dos
 * idiomas a la vez.
 *
 * Aquí cada texto existe en los tres idiomas y el compilador lo obliga:
 * `gl` y `en` son del tipo de `es`, así que si falta una clave, o una función
 * cambia de parámetros, no compila. Sin `t()` y sin tocar `i18n/index.ts`, que
 * comparten varias manos.
 *
 * Los tres idiomas de la app son `es`, `gl` y `en`. En gallego se usan las
 * mismas palabras que el resto del juego (xogo, reto, nodo, obxecto, peza).
 */

const es = {
  juego: {
    cargando: 'Cargando juego…',
    guardando: 'Guardando…',
    avanzando: 'Avanzando…',
    continuar: 'Continuar',
    continuarSiguienteNodo: 'Continuar al siguiente nodo',
    reintentar: 'Reintentar',
  },

  hoja: {
    cerrar: 'CERRAR',
    cerrarJuego: 'Cerrar juego',
    verHistoriaDelNodo: 'Ver historia del nodo',
    verHistoria: 'Ver historia',
    historia: 'Historia',
    guardando: 'Guardando...',
    recogerObjeto: '🎒 RECOGER OBJETO',
    objetoDeMision: 'Objeto de misión',
    coleccionable:
      '¡Has encontrado un objeto coleccionable en esta ubicación! Presiona el botón de abajo para recogerlo y guardarlo en tu mochila.',
    sinJuego:
      'Este nodo no tiene un juego configurado aún. El administrador debe asignarle un tipo de minijuego.',
    respaldoAbrir: '¿Atascado? Escribe el código de respaldo · +2 min',
    respaldoOcultar: 'Ocultar código de respaldo',
    respaldoPlaceholder: 'Escribe el código...',
    respaldoValidar: 'Validar (+2m)',
    envioFallido: 'No se pudo guardar tu avance. Revisa el aviso e inténtalo de nuevo.',
    reintentarEnvio: 'Reintentar',
  },

  /** El aviso que sale al volver de una salida contada. `segundos` = lo que se suma. */
  antiTrampas: {
    salioApp: (segundos: number) =>
      `Saliste de la aplicación durante el reto: empieza de nuevo y se suman ${segundos} s.`,
    selectorApps: (segundos: number) =>
      `Abriste el selector de apps durante el reto: empieza de nuevo y se suman ${segundos} s.`,
  },

  tilt: {
    sensorInicial: 'Botones táctiles disponibles',
    salioAMediaPartida: 'Saliste a media partida: has perdido el intento.',
    pared: 'Pared. Busca otra dirección.',
    objetoRecogido: 'Objeto recogido.',
    sinVidas: 'Has perdido todas las vidas.',
    cayoEnAgujero: 'Caíste en un agujero. Vuelves al inicio.',
    salidaCerrada: 'La salida está cerrada. Recoge todos los objetos.',
    seTerminoElTiempo: 'Se terminó el tiempo.',
    sensorCalibrado: 'Sensor calibrado',
    modoTactil: 'Modo táctil activo',
    calibrar: 'Mantén el móvil cómodo para calibrar',
    sensorNoDisponible: 'Sensor no disponible · usa botones',
    botonesActivos: 'Botones activos · sensor apagado',
    recalibrar: 'Mantén el móvil cómodo para recalibrar',
    bolaAlInicio: 'Bola devuelta al inicio.',
    titulo: 'Laberinto de equilibrio',
    instrucciones: 'Inclina el móvil o usa los botones para alcanzar la salida.',
    leyenda: 'Recoge los objetos ◆, evita los agujeros × y llega a la bandera ⚑.',
    iniciar: 'Iniciar laberinto',
    superado: 'Laberinto superado',
    superadoDetalle: 'Has recogido todos los objetos y alcanzado la salida.',
    intentoTerminado: 'Intento terminado',
    volverAIntentarlo: 'Volver a intentarlo',
    segundos: 'segundos',
    vidas: 'vidas',
    objetos: 'objetos',
    todosLosObjetos: 'Todos los objetos recogidos. Busca la salida.',
    inclinaSuavemente: 'Inclina suavemente el móvil o usa los botones.',
    arriba: 'Arriba',
    izquierda: 'Izquierda',
    abajo: 'Abajo',
    derecha: 'Derecha',
    usarBotones: '¿No responde al inclinar? Usar botones',
    recalibrarBoton: 'Recalibrar',
    volverAlInicio: 'Volver al inicio',
  },

  simon: {
    kicker: 'SIMÓN DICE',
    memoriza: 'Memoriza la secuencia de colores.',
    salioAMediaPrueba: 'Saliste a media prueba: vuelves al nivel 1.',
    observa: (nivel: number, maximo: number) => `Nivel ${nivel} de ${maximo}. Observa...`,
    tuTurno: 'Tu turno: repite la secuencia.',
    fallaste: 'Fallaste. Se vuelve al nivel 1, pero la secuencia es la misma.',
    completa: '¡Secuencia completa!',
    nivelDesbloqueado: (nivel: number) => `¡Bien! Nivel ${nivel} desbloqueado.`,
    nivelDe: (nivel: number, maximo: number) => `Nivel ${nivel} de ${maximo}`,
    empezar: '▶ Empezar',
    reintentar: '↻ Reintentar',
    verSecuencia: '▶ Ver secuencia',
    observando: 'Observando…',
    colores: ['Verde', 'Rojo', 'Azul', 'Ámbar', 'Violeta', 'Cian'] as readonly string[],
  },

  audio: {
    titulo: 'Desafío de audio',
    instrucciones: 'Sopla o haz ruido cerca del micrófono para cargar la barra.',
    activar: 'Activar micrófono',
    sinMicrofono: 'No se pudo acceder al micrófono. Asegúrate de dar permisos.',
  },

  pulso: {
    kicker: 'PULSO DE HIERRO',
    tituloPorDefecto: 'Pulso de hierro',
    instrucciones:
      'Sujeta el móvil lo más quieto posible con una mano. Con la otra, repite la secuencia de colores -crece cada ronda-. Moverte de más reinicia la ronda actual, no la partida.',
    empezar: '▶ Empezar',
    jugarSinSensor: 'Jugar sin sensor de movimiento',
    reinicios: (n: number) => `Reinicios por movimiento: ${n}`,
    rondaSuperada: (ronda: number) => `¡Ronda ${ronda} superada!`,
    sinSensor: 'Sensor de movimiento no disponible.',
    modoTactil: 'Modo táctil',
    sinSensorUsaTactil: 'Sensor no disponible: se usa modo táctil.',
  },

  checkpoint: {
    puntoDeControl: '📍 Punto de control',
    distancia: (metros: number) => `Distancia al punto · zona de ${metros} m`,
    sinCoordenadas: 'Este punto no tiene coordenadas. Puedes continuar.',
    informativo: 'Punto informativo. Lee el texto y continúa.',
    buscandoGps: 'Buscando tu posición GPS…',
    sinPermiso: 'Sin permiso de ubicación. Puedes continuar manualmente.',
    sinGps: 'Este navegador no permite GPS. Puedes continuar manualmente.',
    llegaste: '¡Has llegado al punto de control!',
    acercate: 'Acércate al punto marcado en el mapa.',
    registrando: 'Registrando…',
    heLlegado: '✅ He llegado · Continuar',
    acercateBoton: '🚶 Acércate para continuar',
    gpsFalla: 'Si el GPS falla, pide al monitor el código de emergencia del nodo.',
  },

  motion: {
    titulo: 'Cargar antena',
    brief: 'Baliza sin señal. Cárgala con pulsos para abrir el siguiente tramo.',
    interaccion: 'Interacción',
    listo: 'Pulsa iniciar. Quieto no carga.',
    completado: 'Nodo completado. Pulsa continuar.',
    sobrecarga: 'Sobrecarga. Pulsa más suave.',
    demasiadoFuerte: 'Demasiado fuerte. Carga poco.',
    pulsoValido: 'Pulso válido.',
    toqueValido: 'Toque válido.',
    sensorNoDisponibleTactil: 'Sensor no disponible. Usa táctil.',
    sensorNoDisponible: 'Sensor no disponible.',
    mueveElMovil: 'Pulsa el móvil en movimientos cortos y separados.',
    modoTactilToca: 'Modo táctil. Toca con ritmo.',
    muySeguido: 'Muy seguido. Separa los pulsos.',
    tiempoAgotado: 'Tiempo agotado. Faltaron pulsos válidos.',
    estadoCompletado: 'Nodo completado',
    estadoFallida: 'Carga fallida',
    estadoTactil: 'Modo táctil',
    estadoCargando: 'Cargando',
    estadoSinSensor: 'Sensor no disponible',
    estadoPreparado: 'Preparado',
    carga: 'Carga',
    calor: 'Calor',
    pulsosValidos: 'Pulsos válidos',
    reglaCortos: 'Pulsos cortos',
    reglaCortosDetalle: 'Golpes breves.',
    reglaMedioSegundo: 'Medio segundo',
    reglaMedioSegundoDetalle: 'Pausa entre pulsos.',
    reglaQuieto: 'Quieto no carga',
    reglaQuietoDetalle: 'No hay energía.',
    iniciar: 'Iniciar',
    reintentar: 'Reintentar',
    reiniciar: 'Reiniciar',
    tocar: 'Tocar',
    tactil: 'Táctil',
  },

  circuit: {
    aria: 'Matriz de circuitos',
    patronNoDisponible: 'Patrón fijo no disponible',
    patronRoto: 'El patrón guardado está incompleto o contiene saltos. Corrígelo en el administrador.',
    completado: 'Nodo completado',
    exitoConFallos: (n: number) =>
      `La corriente vuelve a su camino. ${n} ${n === 1 ? 'fallo' : 'fallos'}: +${n * 5}s a tu tiempo.`,
    exitoLimpio: 'La corriente vuelve a su camino, y sin un solo fallo.',
    bloqueada: 'Matriz bloqueada',
    bloqueadaDetalle: 'Has quemado demasiadas celdas. Reinicia y memoriza mejor la secuencia.',
    memoriza: 'Memoriza',
    tuTurno: 'Tu turno',
    preparado: 'Preparado',
    fijate: 'Fíjate en el trazado. Al final se queda entero un momento.',
    marca: (quedan: number) =>
      `Marca las casillas del trazado, en el orden que quieras. ${quedan === 1 ? 'Te queda 1 intento' : `Te quedan ${quedan} intentos`}.`,
    cuentaAtras: (n: number) => `Mira la matriz: la secuencia empieza en ${n}…`,
    tienes: (n: number) => (n === 1 ? 'Tienes 1 intento.' : `Tienes ${n} intentos.`),
    celda: (fila: number, columna: number) => `Celda ${fila}, ${columna}`,
    reiniciar: 'Reiniciar',
    empezarYa: (n: number) => `Empezar ya (${n})`,
    empezar: 'Empezar',
  },

  mosaic: {
    piezaSeleccionada: 'Pieza seleccionada. Toca otra para intercambiarlas.',
    noCoincide: 'No coincide. Observa el lugar real y prueba otra respuesta.',
    noConfigurado: 'Mosaico no configurado',
    noConfiguradoDetalle: 'El administrador debe subir una fotografía válida y revisar la pregunta final.',
    ariaMosaico: 'Mosaico del lugar',
    ariaVistaPrevia: 'Vista previa del mosaico',
    ariaImagenCompletada: 'Imagen completada',
    ariaMosaicoCompletado: 'Mosaico completado',
    ariaMosaicoNoCompletado: 'Mosaico no completado',
    ariaPregunta: 'Pregunta final del mosaico',
    observaElLugar: 'Observa el lugar',
    memorizaLaFoto: 'Memoriza la fotografía antes de que se convierta en piezas.',
    altFotoLugar: 'Fotografía del lugar',
    altFotoCompletada: 'Fotografía completada',
    referenciaRapida: 'Referencia rápida',
    memoriza: 'Memoriza',
    detalleRapido: 'Comprueba un detalle antes de volver al mosaico.',
    observaConCalma: 'Observa con calma las formas, los colores y los detalles principales.',
    volverAlMosaico: 'Volver al mosaico',
    empezarAhora: 'Empezar ahora',
    imagenCompletada: 'Imagen completada',
    todasColocadas: 'Todas las piezas están correctamente colocadas.',
    completado: 'Completado',
    quedaComprobacion: 'Queda una comprobación',
    observaElElemento: 'Observa ahora el elemento real antes de responder.',
    retoCompletado: 'Reto completado',
    yaPuedesContinuar: 'Ya puedes continuar al siguiente punto de la ruta.',
    ahoraResponde: 'Ahora responde a esta pregunta',
    lugarVerificado: 'Lugar verificado',
    lugarVerificadoDetalle: 'La imagen y la comprobación final son correctas. Puedes continuar la ruta.',
    sinMovimientos: 'Sin movimientos',
    sinMovimientosDetalle: 'Se agotó el límite configurado. Observa de nuevo el lugar y vuelve a intentarlo.',
    intentarDeNuevo: 'Intentarlo de nuevo',
    preguntaAyuda: 'Observa el elemento real y elige la respuesta correcta.',
    preguntaSelecciona: 'Selecciona la respuesta que puedas comprobar en el punto donde estás.',
    comprobar: 'Comprobar respuesta',
    descripcionPorDefecto: 'Reconstruye la fotografía observando el lugar real.',
    reconstruye: 'Reconstruye el lugar',
    movimientos: 'movimientos',
    restantes: 'restantes',
    ariaPiezaSeleccionada: (n: number) => `Pieza ${n} seleccionada`,
    ariaSeleccionarPieza: (n: number) => `Seleccionar pieza ${n}`,
    tocaUnaPieza: 'Toca una pieza',
    ahoraTocaOtra: 'Ahora toca otra',
    paraSeleccionarla: 'para seleccionarla.',
    paraIntercambiarlas: 'para intercambiarlas.',
    ariaProgreso: (bien: number, total: number) => `${bien} de ${total} piezas bien colocadas`,
    piezasBien: 'Piezas bien colocadas',
    mezclar: 'Mezclar de nuevo',
    verReferencia: 'Ver referencia · 1,4 s',
  },

  bearing: {
    activaOrientacion: 'Activa orientación',
    sensorBloqueado: 'Sensor bloqueado',
    buscandoHeading: 'Buscando heading',
    mantenEstable: 'Mantén estable',
    cercaDelVector: 'Cerca del vector',
    giraHaciaElVector: 'Gira hacia el vector',
    necesitaToque: 'Safari iPhone necesita un toque para activar orientación real.',
    solicitando: 'Solicitando acceso al sensor.',
    buscando: 'Sensor activo. Esperando primera lectura estable.',
    activa: 'Orientación real activa.',
    silencioso: 'No llega heading. Puedes usar prueba manual discreta.',
    denegado: 'Permiso denegado. Revisa movimiento/orientación en Safari.',
    noSoportado: 'Este navegador no expone DeviceOrientation.',
    sinHttps: 'Abre el runtime desde HTTPS para usar sensores reales.',
    preparando: 'Preparando instrumento.',
    activarSensor: 'Activar sensor',
    pruebaManual: 'Prueba manual',
  },

  teamRelay: {
    titulo: 'Relevo de Equipo',
    juntos: (nombres: string, cuantos: number) =>
      `${nombres} está${cuantos === 1 ? '' : 'n'} aquí contigo.`,
    esperando: 'Esperando a que llegue alguien más del equipo a este punto...',
    companerosAqui: 'Jugadores aquí (contigo):',
    registrando: 'Registrando...',
    mantenPresionado: 'Mantén presionado...',
    validar: 'Validar Relevo',
    esperandoEquipo: 'Esperando equipo',
  },

  cuentaSenales: {
    preguntaPorDefecto: '¿Cuánto cuentas?',
    buscandoGps: 'Buscando tu posición GPS…',
    miraAlrededor: 'Mira alrededor y responde con un número.',
    titulo: '🔢 Cuenta las señales',
    acercate: 'Acércate al punto real',
    zona: (distancia: string, metros: number) => `${distancia} · zona de ${metros} m`,
    altPista: 'Pista',
    penalizacionAcumulada: (segundos: number) => ` · penalización acumulada: ${segundos}s`,
    borrar: 'Borrar',
    comprobando: 'Comprobando…',
    registrando: 'Registrando…',
    responder: '✅ Responder',
  },

  wordTrap: {
    titulo: '🧠 Trampa de palabras',
    leeConCalma: 'Lee con calma: hay opciones casi idénticas.',
  },

  spark: {
    hudSenales: 'SEÑALES',
    hudTiempo: 'TIEMPO',
    hudEcos: 'ECOS',
    ariaSenal: 'Señal',
    ariaSenalFalsa: 'Señal falsa',
    titulo: 'Caza-Señales',
    reglaAntes: 'Toca las chispas ',
    verdes: 'verdes',
    reglaEntre: '. Evita las ',
    rojas: 'rojas',
    reglaDespues: (segundos: number) =>
      `: son señales falsas. Cada roja y cada toque al aire suman ${segundos}s.`,
    objetivo: (aciertos: number, segundos: number) => `${aciertos} señales en ${segundos}s`,
    comenzar: 'Comenzar',
    recuperada: '✅ Señal recuperada',
    aciertosAntes: 'Aciertos: ',
    aciertosDespues: (toques: number) => `/${toques} toques.`,
    falsasAntes: (n: number) => `${n} ${n === 1 ? 'señal falsa' : 'señales falsas'}: `,
    falsasDespues: ' a tu tiempo.',
    sinFallos: 'Ni un solo fallo. Sin penalización.',
    tiempo: (segundos: string) => `Tiempo: ${segundos}s`,
    filaCazadas: 'Señales cazadas',
    filaFalsas: 'Falsas tocadas',
    filaPenalizacion: 'Penalización',
    ninguna: 'ninguna',
    guardando: 'Guardando…',
    continuar: 'Continuar',
    leeElResultado: 'Lee el resultado…',
    tiempoAgotado: '⏱ Tiempo agotado',
    llegaste: (aciertos: number, total: number) =>
      `Llegaste a ${aciertos} de ${total} señales. Inténtalo otra vez.`,
    reintentar: 'Reintentar',
  },
}

export type Textos = typeof es

const gl: Textos = {
  juego: {
    cargando: 'Cargando xogo…',
    guardando: 'Gardando…',
    avanzando: 'Avanzando…',
    continuar: 'Continuar',
    continuarSiguienteNodo: 'Continuar ao seguinte nodo',
    reintentar: 'Reintentar',
  },

  hoja: {
    cerrar: 'PECHAR',
    cerrarJuego: 'Pechar o xogo',
    verHistoriaDelNodo: 'Ver a historia do nodo',
    verHistoria: 'Ver historia',
    historia: 'Historia',
    guardando: 'Gardando...',
    recogerObjeto: '🎒 RECOLLER OBXECTO',
    objetoDeMision: 'Obxecto de misión',
    coleccionable:
      'Atopaches un obxecto coleccionable neste lugar! Preme o botón de abaixo para recollelo e gardalo na túa mochila.',
    sinJuego:
      'Este nodo aínda non ten un xogo configurado. O administrador debe asignarlle un tipo de minixogo.',
    respaldoAbrir: 'Atascado? Escribe o código de respaldo · +2 min',
    respaldoOcultar: 'Agochar o código de respaldo',
    respaldoPlaceholder: 'Escribe o código...',
    respaldoValidar: 'Validar (+2m)',
    envioFallido: 'Non se puido gardar o teu avance. Revisa o aviso e volve tentalo.',
    reintentarEnvio: 'Reintentar',
  },

  antiTrampas: {
    salioApp: (segundos: number) =>
      `Saíches da aplicación durante o reto: comeza de novo e súmanse ${segundos} s.`,
    selectorApps: (segundos: number) =>
      `Abriches o selector de apps durante o reto: comeza de novo e súmanse ${segundos} s.`,
  },

  tilt: {
    sensorInicial: 'Botóns táctiles dispoñibles',
    salioAMediaPartida: 'Saíches a media partida: perdiches o intento.',
    pared: 'Parede. Busca outra dirección.',
    objetoRecogido: 'Obxecto recollido.',
    sinVidas: 'Perdiches todas as vidas.',
    cayoEnAgujero: 'Caíches nun burato. Volves ao inicio.',
    salidaCerrada: 'A saída está pechada. Recolle todos os obxectos.',
    seTerminoElTiempo: 'Rematou o tempo.',
    sensorCalibrado: 'Sensor calibrado',
    modoTactil: 'Modo táctil activo',
    calibrar: 'Mantén o móbil cómodo para calibrar',
    sensorNoDisponible: 'Sensor non dispoñible · usa botóns',
    botonesActivos: 'Botóns activos · sensor apagado',
    recalibrar: 'Mantén o móbil cómodo para recalibrar',
    bolaAlInicio: 'Bóla devolta ao inicio.',
    titulo: 'Labirinto de equilibrio',
    instrucciones: 'Inclina o móbil ou usa os botóns para chegar á saída.',
    leyenda: 'Recolle os obxectos ◆, evita os buratos × e chega á bandeira ⚑.',
    iniciar: 'Iniciar labirinto',
    superado: 'Labirinto superado',
    superadoDetalle: 'Recolliches todos os obxectos e chegaches á saída.',
    intentoTerminado: 'Intento rematado',
    volverAIntentarlo: 'Intentalo de novo',
    segundos: 'segundos',
    vidas: 'vidas',
    objetos: 'obxectos',
    todosLosObjetos: 'Todos os obxectos recollidos. Busca a saída.',
    inclinaSuavemente: 'Inclina suavemente o móbil ou usa os botóns.',
    arriba: 'Arriba',
    izquierda: 'Esquerda',
    abajo: 'Abaixo',
    derecha: 'Dereita',
    usarBotones: 'Non responde ao inclinar? Usar botóns',
    recalibrarBoton: 'Recalibrar',
    volverAlInicio: 'Volver ao inicio',
  },

  simon: {
    kicker: 'SIMÓN DI',
    memoriza: 'Memoriza a secuencia de cores.',
    salioAMediaPrueba: 'Saíches a media proba: volves ao nivel 1.',
    observa: (nivel: number, maximo: number) => `Nivel ${nivel} de ${maximo}. Observa...`,
    tuTurno: 'A túa quenda: repite a secuencia.',
    fallaste: 'Fallaches. Volves ao nivel 1, pero a secuencia é a mesma.',
    completa: 'Secuencia completa!',
    nivelDesbloqueado: (nivel: number) => `Ben! Nivel ${nivel} desbloqueado.`,
    nivelDe: (nivel: number, maximo: number) => `Nivel ${nivel} de ${maximo}`,
    empezar: '▶ Comezar',
    reintentar: '↻ Reintentar',
    verSecuencia: '▶ Ver secuencia',
    observando: 'Observando…',
    colores: ['Verde', 'Vermello', 'Azul', 'Ámbar', 'Violeta', 'Cian'] as readonly string[],
  },

  audio: {
    titulo: 'Reto de audio',
    instrucciones: 'Sopra ou fai ruído preto do micrófono para cargar a barra.',
    activar: 'Activar micrófono',
    sinMicrofono: 'Non se puido acceder ao micrófono. Asegúrate de dar os permisos.',
  },

  pulso: {
    kicker: 'PULSO DE FERRO',
    tituloPorDefecto: 'Pulso de ferro',
    instrucciones:
      'Suxeita o móbil o máis quieto posible cunha man. Coa outra, repite a secuencia de cores -crece cada rolda-. Moverte de máis reinicia a rolda actual, non a partida.',
    empezar: '▶ Comezar',
    jugarSinSensor: 'Xogar sen sensor de movemento',
    reinicios: (n: number) => `Reinicios por movemento: ${n}`,
    rondaSuperada: (ronda: number) => `Rolda ${ronda} superada!`,
    sinSensor: 'Sensor de movemento non dispoñible.',
    modoTactil: 'Modo táctil',
    sinSensorUsaTactil: 'Sensor non dispoñible: úsase o modo táctil.',
  },

  checkpoint: {
    puntoDeControl: '📍 Punto de control',
    distancia: (metros: number) => `Distancia ao punto · zona de ${metros} m`,
    sinCoordenadas: 'Este punto non ten coordenadas. Podes continuar.',
    informativo: 'Punto informativo. Le o texto e continúa.',
    buscandoGps: 'Buscando a túa posición GPS…',
    sinPermiso: 'Sen permiso de ubicación. Podes continuar manualmente.',
    sinGps: 'Este navegador non permite GPS. Podes continuar manualmente.',
    llegaste: 'Chegaches ao punto de control!',
    acercate: 'Achégate ao punto marcado no mapa.',
    registrando: 'Rexistrando…',
    heLlegado: '✅ Cheguei · Continuar',
    acercateBoton: '🚶 Achégate para continuar',
    gpsFalla: 'Se o GPS falla, pídelle ao monitor o código de emerxencia do nodo.',
  },

  motion: {
    titulo: 'Cargar antena',
    brief: 'Baliza sen sinal. Cárgaa con pulsos para abrir o seguinte treito.',
    interaccion: 'Interacción',
    listo: 'Preme iniciar. Quieto non carga.',
    completado: 'Nodo completado. Preme continuar.',
    sobrecarga: 'Sobrecarga. Preme máis suave.',
    demasiadoFuerte: 'Demasiado forte. Carga pouco.',
    pulsoValido: 'Pulso válido.',
    toqueValido: 'Toque válido.',
    sensorNoDisponibleTactil: 'Sensor non dispoñible. Usa o táctil.',
    sensorNoDisponible: 'Sensor non dispoñible.',
    mueveElMovil: 'Move o móbil con golpes curtos e separados.',
    modoTactilToca: 'Modo táctil. Toca co ritmo.',
    muySeguido: 'Moi seguido. Separa os pulsos.',
    tiempoAgotado: 'Tempo esgotado. Faltaron pulsos válidos.',
    estadoCompletado: 'Nodo completado',
    estadoFallida: 'Carga fallida',
    estadoTactil: 'Modo táctil',
    estadoCargando: 'Cargando',
    estadoSinSensor: 'Sensor non dispoñible',
    estadoPreparado: 'Preparado',
    carga: 'Carga',
    calor: 'Calor',
    pulsosValidos: 'Pulsos válidos',
    reglaCortos: 'Pulsos curtos',
    reglaCortosDetalle: 'Golpes breves.',
    reglaMedioSegundo: 'Medio segundo',
    reglaMedioSegundoDetalle: 'Pausa entre pulsos.',
    reglaQuieto: 'Quieto non carga',
    reglaQuietoDetalle: 'Non hai enerxía.',
    iniciar: 'Iniciar',
    reintentar: 'Reintentar',
    reiniciar: 'Reiniciar',
    tocar: 'Tocar',
    tactil: 'Táctil',
  },

  circuit: {
    aria: 'Matriz de circuítos',
    patronNoDisponible: 'Patrón fixo non dispoñible',
    patronRoto: 'O patrón gardado está incompleto ou contén saltos. Corríxeo no administrador.',
    completado: 'Nodo completado',
    exitoConFallos: (n: number) =>
      `A corrente volve ao seu camiño. ${n} ${n === 1 ? 'fallo' : 'fallos'}: +${n * 5}s ao teu tempo.`,
    exitoLimpio: 'A corrente volve ao seu camiño, e sen un só fallo.',
    bloqueada: 'Matriz bloqueada',
    bloqueadaDetalle: 'Queimaches demasiadas celas. Reinicia e memoriza mellor a secuencia.',
    memoriza: 'Memoriza',
    tuTurno: 'A túa quenda',
    preparado: 'Preparado',
    fijate: 'Fíxate no trazado. Ao final quédase enteiro un momento.',
    marca: (quedan: number) =>
      `Marca as casas do trazado, na orde que queiras. ${quedan === 1 ? 'Quédache 1 intento' : `Quédanche ${quedan} intentos`}.`,
    cuentaAtras: (n: number) => `Mira a matriz: a secuencia comeza en ${n}…`,
    tienes: (n: number) => (n === 1 ? 'Tes 1 intento.' : `Tes ${n} intentos.`),
    celda: (fila: number, columna: number) => `Cela ${fila}, ${columna}`,
    reiniciar: 'Reiniciar',
    empezarYa: (n: number) => `Comezar xa (${n})`,
    empezar: 'Comezar',
  },

  mosaic: {
    piezaSeleccionada: 'Peza seleccionada. Toca outra para intercambialas.',
    noCoincide: 'Non coincide. Observa o lugar real e proba outra resposta.',
    noConfigurado: 'Mosaico non configurado',
    noConfiguradoDetalle: 'O administrador debe subir unha fotografía válida e revisar a pregunta final.',
    ariaMosaico: 'Mosaico do lugar',
    ariaVistaPrevia: 'Vista previa do mosaico',
    ariaImagenCompletada: 'Imaxe completada',
    ariaMosaicoCompletado: 'Mosaico completado',
    ariaMosaicoNoCompletado: 'Mosaico non completado',
    ariaPregunta: 'Pregunta final do mosaico',
    observaElLugar: 'Observa o lugar',
    memorizaLaFoto: 'Memoriza a fotografía antes de que se converta en pezas.',
    altFotoLugar: 'Fotografía do lugar',
    altFotoCompletada: 'Fotografía completada',
    referenciaRapida: 'Referencia rápida',
    memoriza: 'Memoriza',
    detalleRapido: 'Comproba un detalle antes de volver ao mosaico.',
    observaConCalma: 'Observa con calma as formas, as cores e os detalles principais.',
    volverAlMosaico: 'Volver ao mosaico',
    empezarAhora: 'Comezar agora',
    imagenCompletada: 'Imaxe completada',
    todasColocadas: 'Todas as pezas están correctamente colocadas.',
    completado: 'Completado',
    quedaComprobacion: 'Queda unha comprobación',
    observaElElemento: 'Observa agora o elemento real antes de responder.',
    retoCompletado: 'Reto completado',
    yaPuedesContinuar: 'Xa podes continuar ao seguinte punto da ruta.',
    ahoraResponde: 'Agora responde a esta pregunta',
    lugarVerificado: 'Lugar verificado',
    lugarVerificadoDetalle: 'A imaxe e a comprobación final son correctas. Podes continuar a ruta.',
    sinMovimientos: 'Sen movementos',
    sinMovimientosDetalle: 'Esgotouse o límite configurado. Observa de novo o lugar e volve tentalo.',
    intentarDeNuevo: 'Intentalo de novo',
    preguntaAyuda: 'Observa o elemento real e escolle a resposta correcta.',
    preguntaSelecciona: 'Selecciona a resposta que poidas comprobar no punto onde estás.',
    comprobar: 'Comprobar resposta',
    descripcionPorDefecto: 'Reconstrúe a fotografía observando o lugar real.',
    reconstruye: 'Reconstrúe o lugar',
    movimientos: 'movementos',
    restantes: 'restantes',
    ariaPiezaSeleccionada: (n: number) => `Peza ${n} seleccionada`,
    ariaSeleccionarPieza: (n: number) => `Seleccionar peza ${n}`,
    tocaUnaPieza: 'Toca unha peza',
    ahoraTocaOtra: 'Agora toca outra',
    paraSeleccionarla: 'para seleccionala.',
    paraIntercambiarlas: 'para intercambialas.',
    ariaProgreso: (bien: number, total: number) => `${bien} de ${total} pezas ben colocadas`,
    piezasBien: 'Pezas ben colocadas',
    mezclar: 'Mesturar de novo',
    verReferencia: 'Ver referencia · 1,4 s',
  },

  bearing: {
    activaOrientacion: 'Activa a orientación',
    sensorBloqueado: 'Sensor bloqueado',
    buscandoHeading: 'Buscando rumbo',
    mantenEstable: 'Mantén estable',
    cercaDelVector: 'Preto do vector',
    giraHaciaElVector: 'Xira cara ao vector',
    necesitaToque: 'Safari en iPhone precisa un toque para activar a orientación real.',
    solicitando: 'Solicitando acceso ao sensor.',
    buscando: 'Sensor activo. Agardando a primeira lectura estable.',
    activa: 'Orientación real activa.',
    silencioso: 'Non chega o rumbo. Podes usar a proba manual discreta.',
    denegado: 'Permiso denegado. Revisa movemento/orientación en Safari.',
    noSoportado: 'Este navegador non expón DeviceOrientation.',
    sinHttps: 'Abre o runtime desde HTTPS para usar sensores reais.',
    preparando: 'Preparando o instrumento.',
    activarSensor: 'Activar sensor',
    pruebaManual: 'Proba manual',
  },

  teamRelay: {
    titulo: 'Relevo de equipo',
    juntos: (nombres: string, cuantos: number) =>
      `${nombres} está${cuantos === 1 ? '' : 'n'} aquí contigo.`,
    esperando: 'Agardando a que chegue alguén máis do equipo a este punto...',
    companerosAqui: 'Xogadores aquí (contigo):',
    registrando: 'Rexistrando...',
    mantenPresionado: 'Mantén premido...',
    validar: 'Validar relevo',
    esperandoEquipo: 'Agardando polo equipo',
  },

  cuentaSenales: {
    preguntaPorDefecto: 'Cantas contas?',
    buscandoGps: 'Buscando a túa posición GPS…',
    miraAlrededor: 'Mira ao teu redor e responde cun número.',
    titulo: '🔢 Conta as sinais',
    acercate: 'Achégate ao punto real',
    zona: (distancia: string, metros: number) => `${distancia} · zona de ${metros} m`,
    altPista: 'Pista',
    penalizacionAcumulada: (segundos: number) => ` · penalización acumulada: ${segundos}s`,
    borrar: 'Borrar',
    comprobando: 'Comprobando…',
    registrando: 'Rexistrando…',
    responder: '✅ Responder',
  },

  wordTrap: {
    titulo: '🧠 Trampa de palabras',
    leeConCalma: 'Le con calma: hai opcións case idénticas.',
  },

  spark: {
    hudSenales: 'SINAIS',
    hudTiempo: 'TEMPO',
    hudEcos: 'ECOS',
    ariaSenal: 'Sinal',
    ariaSenalFalsa: 'Sinal falsa',
    titulo: 'Caza-Señales',
    reglaAntes: 'Toca as chispas ',
    verdes: 'verdes',
    reglaEntre: '. Evita as ',
    rojas: 'vermellas',
    reglaDespues: (segundos: number) =>
      `: son sinais falsas. Cada vermella e cada toque ao aire soman ${segundos}s.`,
    objetivo: (aciertos: number, segundos: number) => `${aciertos} sinais en ${segundos}s`,
    comenzar: 'Comezar',
    recuperada: '✅ Sinal recuperado',
    aciertosAntes: 'Acertos: ',
    aciertosDespues: (toques: number) => `/${toques} toques.`,
    falsasAntes: (n: number) => `${n} ${n === 1 ? 'sinal falsa' : 'sinais falsas'}: `,
    falsasDespues: ' ao teu tempo.',
    sinFallos: 'Sen un só fallo. Sen penalización.',
    tiempo: (segundos: string) => `Tempo: ${segundos}s`,
    filaCazadas: 'Sinais cazadas',
    filaFalsas: 'Falsas tocadas',
    filaPenalizacion: 'Penalización',
    ninguna: 'ningunha',
    guardando: 'Gardando…',
    continuar: 'Continuar',
    leeElResultado: 'Le o resultado…',
    tiempoAgotado: '⏱ Tempo esgotado',
    llegaste: (aciertos: number, total: number) =>
      `Chegaches a ${aciertos} de ${total} sinais. Próbao outra vez.`,
    reintentar: 'Reintentar',
  },
}

const en: Textos = {
  juego: {
    cargando: 'Loading game…',
    guardando: 'Saving…',
    avanzando: 'Moving on…',
    continuar: 'Continue',
    continuarSiguienteNodo: 'Continue to the next node',
    reintentar: 'Try again',
  },

  hoja: {
    cerrar: 'CLOSE',
    cerrarJuego: 'Close game',
    verHistoriaDelNodo: 'View node story',
    verHistoria: 'View story',
    historia: 'Story',
    guardando: 'Saving...',
    recogerObjeto: '🎒 COLLECT ITEM',
    objetoDeMision: 'Mission item',
    coleccionable:
      'You found a collectible item at this location! Press the button below to pick it up and put it in your backpack.',
    sinJuego:
      'This node has no game set up yet. The administrator must assign it a minigame type.',
    respaldoAbrir: 'Stuck? Enter the backup code · +2 min',
    respaldoOcultar: 'Hide backup code',
    respaldoPlaceholder: 'Enter the code...',
    respaldoValidar: 'Check (+2m)',
    envioFallido: 'Your progress could not be saved. Check the notice and try again.',
    reintentarEnvio: 'Try again',
  },

  antiTrampas: {
    salioApp: (segundos: number) =>
      `You left the app during the challenge: it starts over and ${segundos} s are added.`,
    selectorApps: (segundos: number) =>
      `You opened the app switcher during the challenge: it starts over and ${segundos} s are added.`,
  },

  tilt: {
    sensorInicial: 'Touch buttons available',
    salioAMediaPartida: 'You left mid-game: the attempt is lost.',
    pared: 'Wall. Try another direction.',
    objetoRecogido: 'Item collected.',
    sinVidas: 'You have lost all your lives.',
    cayoEnAgujero: 'You fell into a hole. Back to the start.',
    salidaCerrada: 'The exit is closed. Collect every item first.',
    seTerminoElTiempo: 'Time is up.',
    sensorCalibrado: 'Sensor calibrated',
    modoTactil: 'Touch mode on',
    calibrar: 'Hold the phone comfortably to calibrate',
    sensorNoDisponible: 'Sensor unavailable · use the buttons',
    botonesActivos: 'Buttons on · sensor off',
    recalibrar: 'Hold the phone comfortably to recalibrate',
    bolaAlInicio: 'Ball sent back to the start.',
    titulo: 'Balance maze',
    instrucciones: 'Tilt the phone or use the buttons to reach the exit.',
    leyenda: 'Collect the items ◆, avoid the holes × and reach the flag ⚑.',
    iniciar: 'Start maze',
    superado: 'Maze completed',
    superadoDetalle: 'You collected every item and reached the exit.',
    intentoTerminado: 'Attempt over',
    volverAIntentarlo: 'Try again',
    segundos: 'seconds',
    vidas: 'lives',
    objetos: 'items',
    todosLosObjetos: 'All items collected. Find the exit.',
    inclinaSuavemente: 'Tilt the phone gently or use the buttons.',
    arriba: 'Up',
    izquierda: 'Left',
    abajo: 'Down',
    derecha: 'Right',
    usarBotones: "Not responding to tilt? Use buttons",
    recalibrarBoton: 'Recalibrate',
    volverAlInicio: 'Back to start',
  },

  simon: {
    kicker: 'SIMON SAYS',
    memoriza: 'Memorise the colour sequence.',
    salioAMediaPrueba: 'You left mid-game: back to level 1.',
    observa: (nivel: number, maximo: number) => `Level ${nivel} of ${maximo}. Watch...`,
    tuTurno: 'Your turn: repeat the sequence.',
    fallaste: 'Wrong. Back to level 1, but the sequence is the same.',
    completa: 'Sequence complete!',
    nivelDesbloqueado: (nivel: number) => `Well done! Level ${nivel} unlocked.`,
    nivelDe: (nivel: number, maximo: number) => `Level ${nivel} of ${maximo}`,
    empezar: '▶ Start',
    reintentar: '↻ Try again',
    verSecuencia: '▶ Show sequence',
    observando: 'Watching…',
    colores: ['Green', 'Red', 'Blue', 'Amber', 'Violet', 'Cyan'] as readonly string[],
  },

  audio: {
    titulo: 'Audio challenge',
    instrucciones: 'Blow or make noise near the microphone to fill the bar.',
    activar: 'Turn on microphone',
    sinMicrofono: 'The microphone could not be accessed. Make sure you grant permission.',
  },

  pulso: {
    kicker: 'IRON PULSE',
    tituloPorDefecto: 'Iron pulse',
    instrucciones:
      'Hold the phone as still as you can with one hand. With the other, repeat the colour sequence -it grows every round-. Moving too much restarts the current round, not the whole game.',
    empezar: '▶ Start',
    jugarSinSensor: 'Play without the motion sensor',
    reinicios: (n: number) => `Restarts caused by movement: ${n}`,
    rondaSuperada: (ronda: number) => `Round ${ronda} cleared!`,
    sinSensor: 'Motion sensor unavailable.',
    modoTactil: 'Touch mode',
    sinSensorUsaTactil: 'Sensor unavailable: touch mode is used.',
  },

  checkpoint: {
    puntoDeControl: '📍 Checkpoint',
    distancia: (metros: number) => `Distance to the point · ${metros} m zone`,
    sinCoordenadas: 'This point has no coordinates. You can continue.',
    informativo: 'Information point. Read the text and continue.',
    buscandoGps: 'Finding your GPS position…',
    sinPermiso: 'Location permission denied. You can continue manually.',
    sinGps: 'This browser does not support GPS. You can continue manually.',
    llegaste: 'You have reached the checkpoint!',
    acercate: 'Get closer to the point marked on the map.',
    registrando: 'Saving…',
    heLlegado: "✅ I'm here · Continue",
    acercateBoton: '🚶 Get closer to continue',
    gpsFalla: "If the GPS fails, ask the organiser for the node's emergency code.",
  },

  motion: {
    titulo: 'Charge the antenna',
    brief: 'Beacon with no signal. Charge it with pulses to open the next stretch.',
    interaccion: 'Interaction',
    listo: 'Press start. Standing still does not charge.',
    completado: 'Node completed. Press continue.',
    sobrecarga: 'Overload. Pulse more gently.',
    demasiadoFuerte: 'Too hard. It charges very little.',
    pulsoValido: 'Valid pulse.',
    toqueValido: 'Valid tap.',
    sensorNoDisponibleTactil: 'Sensor unavailable. Use touch.',
    sensorNoDisponible: 'Sensor unavailable.',
    mueveElMovil: 'Pulse the phone with short, separate movements.',
    modoTactilToca: 'Touch mode. Tap to the rhythm.',
    muySeguido: 'Too close together. Space the pulses out.',
    tiempoAgotado: 'Time is up. Not enough valid pulses.',
    estadoCompletado: 'Node completed',
    estadoFallida: 'Charge failed',
    estadoTactil: 'Touch mode',
    estadoCargando: 'Charging',
    estadoSinSensor: 'Sensor unavailable',
    estadoPreparado: 'Ready',
    carga: 'Charge',
    calor: 'Heat',
    pulsosValidos: 'Valid pulses',
    reglaCortos: 'Short pulses',
    reglaCortosDetalle: 'Brief knocks.',
    reglaMedioSegundo: 'Half a second',
    reglaMedioSegundoDetalle: 'Pause between pulses.',
    reglaQuieto: 'Still does not charge',
    reglaQuietoDetalle: 'No energy.',
    iniciar: 'Start',
    reintentar: 'Try again',
    reiniciar: 'Restart',
    tocar: 'Tap',
    tactil: 'Touch',
  },

  circuit: {
    aria: 'Circuit matrix',
    patronNoDisponible: 'Fixed pattern unavailable',
    patronRoto: 'The saved pattern is incomplete or has jumps. Fix it in the admin panel.',
    completado: 'Node completed',
    exitoConFallos: (n: number) =>
      `The current flows again. ${n} ${n === 1 ? 'mistake' : 'mistakes'}: +${n * 5}s to your time.`,
    exitoLimpio: 'The current flows again, without a single mistake.',
    bloqueada: 'Matrix locked',
    bloqueadaDetalle: 'You burned too many cells. Restart and memorise the sequence better.',
    memoriza: 'Memorise',
    tuTurno: 'Your turn',
    preparado: 'Ready',
    fijate: 'Look at the path. At the end it stays fully lit for a moment.',
    marca: (quedan: number) =>
      `Tap the cells of the path, in any order. You have ${quedan} ${quedan === 1 ? 'try' : 'tries'} left.`,
    cuentaAtras: (n: number) => `Watch the matrix: the sequence starts in ${n}…`,
    tienes: (n: number) => `You have ${n} ${n === 1 ? 'try' : 'tries'}.`,
    celda: (fila: number, columna: number) => `Cell ${fila}, ${columna}`,
    reiniciar: 'Restart',
    empezarYa: (n: number) => `Start now (${n})`,
    empezar: 'Start',
  },

  mosaic: {
    piezaSeleccionada: 'Piece selected. Tap another one to swap them.',
    noCoincide: "That doesn't match. Look at the real place and try another answer.",
    noConfigurado: 'Mosaic not set up',
    noConfiguradoDetalle: 'The administrator must upload a valid photograph and check the final question.',
    ariaMosaico: 'Place mosaic',
    ariaVistaPrevia: 'Mosaic preview',
    ariaImagenCompletada: 'Completed picture',
    ariaMosaicoCompletado: 'Mosaic completed',
    ariaMosaicoNoCompletado: 'Mosaic not completed',
    ariaPregunta: 'Final mosaic question',
    observaElLugar: 'Look at the place',
    memorizaLaFoto: 'Memorise the photograph before it turns into pieces.',
    altFotoLugar: 'Photograph of the place',
    altFotoCompletada: 'Completed photograph',
    referenciaRapida: 'Quick reference',
    memoriza: 'Memorise',
    detalleRapido: 'Check one detail before going back to the mosaic.',
    observaConCalma: 'Take your time over the shapes, the colours and the main details.',
    volverAlMosaico: 'Back to the mosaic',
    empezarAhora: 'Start now',
    imagenCompletada: 'Picture completed',
    todasColocadas: 'All the pieces are in the right place.',
    completado: 'Completed',
    quedaComprobacion: 'One check left',
    observaElElemento: 'Now look at the real thing before you answer.',
    retoCompletado: 'Challenge completed',
    yaPuedesContinuar: 'You can now go on to the next point on the route.',
    ahoraResponde: 'Now answer this question',
    lugarVerificado: 'Place verified',
    lugarVerificadoDetalle: 'The picture and the final check are correct. You can continue along the route.',
    sinMovimientos: 'Out of moves',
    sinMovimientosDetalle: 'The configured limit has run out. Look at the place again and try once more.',
    intentarDeNuevo: 'Try again',
    preguntaAyuda: 'Look at the real thing and choose the right answer.',
    preguntaSelecciona: 'Choose the answer you can check where you are standing.',
    comprobar: 'Check answer',
    descripcionPorDefecto: 'Rebuild the photograph by looking at the real place.',
    reconstruye: 'Rebuild the place',
    movimientos: 'moves',
    restantes: 'left',
    ariaPiezaSeleccionada: (n: number) => `Piece ${n} selected`,
    ariaSeleccionarPieza: (n: number) => `Select piece ${n}`,
    tocaUnaPieza: 'Tap a piece',
    ahoraTocaOtra: 'Now tap another',
    paraSeleccionarla: 'to select it.',
    paraIntercambiarlas: 'to swap them.',
    ariaProgreso: (bien: number, total: number) => `${bien} of ${total} pieces in place`,
    piezasBien: 'Pieces in place',
    mezclar: 'Shuffle again',
    verReferencia: 'See reference · 1.4 s',
  },

  bearing: {
    activaOrientacion: 'Enable orientation',
    sensorBloqueado: 'Sensor blocked',
    buscandoHeading: 'Looking for heading',
    mantenEstable: 'Hold steady',
    cercaDelVector: 'Close to the vector',
    giraHaciaElVector: 'Turn towards the vector',
    necesitaToque: 'Safari on iPhone needs a tap to turn real orientation on.',
    solicitando: 'Requesting access to the sensor.',
    buscando: 'Sensor on. Waiting for the first steady reading.',
    activa: 'Real orientation on.',
    silencioso: 'No heading is coming in. You can use the discreet manual test.',
    denegado: 'Permission denied. Check motion/orientation in Safari.',
    noSoportado: 'This browser does not expose DeviceOrientation.',
    sinHttps: 'Open the runtime over HTTPS to use the real sensors.',
    preparando: 'Getting the instrument ready.',
    activarSensor: 'Turn on sensor',
    pruebaManual: 'Manual test',
  },

  teamRelay: {
    titulo: 'Team relay',
    juntos: (nombres: string, cuantos: number) =>
      `${nombres} ${cuantos === 1 ? 'is' : 'are'} here with you.`,
    esperando: 'Waiting for someone else from the team to reach this point...',
    companerosAqui: 'Players here (incl. you):',
    registrando: 'Saving...',
    mantenPresionado: 'Keep pressing...',
    validar: 'Confirm relay',
    esperandoEquipo: 'Waiting for the team',
  },

  cuentaSenales: {
    preguntaPorDefecto: 'How many can you count?',
    buscandoGps: 'Finding your GPS position…',
    miraAlrededor: 'Look around and answer with a number.',
    titulo: '🔢 Count the signals',
    acercate: 'Get closer to the real spot',
    zona: (distancia: string, metros: number) => `${distancia} · ${metros} m zone`,
    altPista: 'Hint',
    penalizacionAcumulada: (segundos: number) => ` · penalty so far: ${segundos}s`,
    borrar: 'Clear',
    comprobando: 'Checking…',
    registrando: 'Saving…',
    responder: '✅ Answer',
  },

  wordTrap: {
    titulo: '🧠 Word trap',
    leeConCalma: 'Read carefully: some options are almost identical.',
  },

  spark: {
    hudSenales: 'SIGNALS',
    hudTiempo: 'TIME',
    hudEcos: 'ECHOES',
    ariaSenal: 'Signal',
    ariaSenalFalsa: 'False signal',
    titulo: 'Signal Hunt',
    reglaAntes: 'Tap the ',
    verdes: 'green',
    reglaEntre: ' sparks. Avoid the ',
    rojas: 'red',
    reglaDespues: (segundos: number) =>
      ' ones: they are false signals. Every red one and every tap on empty air adds ' +
      `${segundos}s.`,
    objetivo: (aciertos: number, segundos: number) => `${aciertos} signals in ${segundos}s`,
    comenzar: 'Start',
    recuperada: '✅ Signal recovered',
    aciertosAntes: 'Hits: ',
    aciertosDespues: (toques: number) => `/${toques} taps.`,
    falsasAntes: (n: number) => `${n} false ${n === 1 ? 'signal' : 'signals'}: `,
    falsasDespues: ' added to your time.',
    sinFallos: 'Not a single miss. No penalty.',
    tiempo: (segundos: string) => `Time: ${segundos}s`,
    filaCazadas: 'Signals caught',
    filaFalsas: 'False ones tapped',
    filaPenalizacion: 'Penalty',
    ninguna: 'none',
    guardando: 'Saving…',
    continuar: 'Continue',
    leeElResultado: 'Read the result…',
    tiempoAgotado: '⏱ Time is up',
    llegaste: (aciertos: number, total: number) =>
      `You got ${aciertos} of ${total} signals. Try again.`,
    reintentar: 'Try again',
  },
}

const TEXTOS: Record<Locale, Textos> = { es, gl, en }

/** Los textos de un idioma. Un idioma desconocido cae en castellano. */
export function textosDe(locale: string | null | undefined): Textos {
  return TEXTOS[(locale as Locale) in TEXTOS ? (locale as Locale) : 'es']
}

/** Para los tests y para quien necesite recorrerlos todos. */
export const TEXTOS_DEL_JUGADOR: Readonly<Record<Locale, Textos>> = TEXTOS
